jobs:
- name: hello-world
  plan:
  - task: get-mad
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Bahumbug!"]
